// Generated by gencpp from file rrbot_control/IKRequest.msg
// DO NOT EDIT!


#ifndef RRBOT_CONTROL_MESSAGE_IKREQUEST_H
#define RRBOT_CONTROL_MESSAGE_IKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rrbot_control
{
template <class ContainerAllocator>
struct IKRequest_
{
  typedef IKRequest_<ContainerAllocator> Type;

  IKRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , alpha(0.0)
    , beta(0.0)
    , gamma(0.0)  {
    }
  IKRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , alpha(0.0)
    , beta(0.0)
    , gamma(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _alpha_type;
  _alpha_type alpha;

   typedef float _beta_type;
  _beta_type beta;

   typedef float _gamma_type;
  _gamma_type gamma;





  typedef boost::shared_ptr< ::rrbot_control::IKRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rrbot_control::IKRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IKRequest_

typedef ::rrbot_control::IKRequest_<std::allocator<void> > IKRequest;

typedef boost::shared_ptr< ::rrbot_control::IKRequest > IKRequestPtr;
typedef boost::shared_ptr< ::rrbot_control::IKRequest const> IKRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rrbot_control::IKRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rrbot_control::IKRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rrbot_control::IKRequest_<ContainerAllocator1> & lhs, const ::rrbot_control::IKRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.alpha == rhs.alpha &&
    lhs.beta == rhs.beta &&
    lhs.gamma == rhs.gamma;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rrbot_control::IKRequest_<ContainerAllocator1> & lhs, const ::rrbot_control::IKRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rrbot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rrbot_control::IKRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rrbot_control::IKRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rrbot_control::IKRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rrbot_control::IKRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rrbot_control::IKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rrbot_control::IKRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rrbot_control::IKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a80a1671d4b1c7800db798b2cad836f8";
  }

  static const char* value(const ::rrbot_control::IKRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa80a1671d4b1c780ULL;
  static const uint64_t static_value2 = 0x0db798b2cad836f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::rrbot_control::IKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rrbot_control/IKRequest";
  }

  static const char* value(const ::rrbot_control::IKRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rrbot_control::IKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 alpha\n"
"float32 beta\n"
"float32 gamma\n"
;
  }

  static const char* value(const ::rrbot_control::IKRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rrbot_control::IKRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.alpha);
      stream.next(m.beta);
      stream.next(m.gamma);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IKRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rrbot_control::IKRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rrbot_control::IKRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "alpha: ";
    Printer<float>::stream(s, indent + "  ", v.alpha);
    s << indent << "beta: ";
    Printer<float>::stream(s, indent + "  ", v.beta);
    s << indent << "gamma: ";
    Printer<float>::stream(s, indent + "  ", v.gamma);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RRBOT_CONTROL_MESSAGE_IKREQUEST_H
